namespace TerrariaBot
{
    // From https://terraria.gamepedia.com/Tile_IDs
    public enum Bloc
    {
        // Blocs
        Nothing = 0, // Empty or dirt
        StoneBlock = 1,
        Grass = 2,
        CorruptGrass = 23,
        EbonstoneBlock = 25,
        Wood = 30,
        GrayBrick = 38,
        RedBrick = 39,
        ClayBlock = 40,
        BlueBrick = 41,
        GreenBrick = 43,
        PinkBrick = 44,
        GoldBrick = 45,
        SilverBrick = 46,
        CopperBrick = 47,
        SandBlock = 53,
        Glass = 54,
        AshBlock = 57,
        MudBlock = 59,
        JungleGrass = 60,
        SapphireBlock = 63,
        RubyBlock = 64,
        EmeraldBlock = 65,
        TopazBlock = 66,
        AmethystBlock = 67,
        DiamondBlock = 68,
        MushroomGrass = 70,
        ObsidianBrick = 75,
        HellstoneBrick = 76,
        HallowedGrass = 109,
        EbonsandBlock = 112,
        PearlsandBlock = 116,
        PearlstoneBlock = 117,
        PearlstoneBrick = 118,
        IridescentBrick = 119,
        MudstoneBrick = 120,
        CobaltBrick = 121,
        MythrilBrick = 122,
        SiltBlock = 123,
        WoodenBeam = 124,
        IceRodBlock = 127,
        ActiveStoneBlack = 130,
        DartTrap = 137,
        DemoniteBrick = 140,
        CandleCaneBlock = 145,
        GreenCandyCanBlock = 146,
        SnowBlock = 147,
        SnowBrick = 148,
        AdamantiteBeam = 150,
        SandstoneBrick = 151,
        EbonstoneBrick = 152,
        RedStucco = 153,
        YellowStucco = 154,
        GreenStucco = 155,
        GrayStucco = 156,
        Ebonwood = 157,
        RichMahogany = 158,
        Pearlwood = 159,
        RainbowBrick = 160,
        IceBlock = 161,
        PurpleIceBlock = 163,
        PinkIceBlock = 164,
        PineTreeBlock = 170,
        TinBrick = 175,
        TungstenBrick = 176,
        PlatiniumBrick = 177,
        TealMoss = 179,
        ChartreuseMoss = 180,
        RedMoss = 181,
        BlueMoss = 182,
        PurpleMoss = 183,
        CactusPlaced = 188,
        Cloud = 189,
        GlowingMushroomPlaced  = 190,


        // Thin ice
        ThinIce = 162,

        // Platform
        Platform = 19,

        // Doors
        ClosedDoor = 10,
        OpenedDoor = 11,

        // Trees
        Tree = 5,

        // Ore
        IronOre = 6,
        CopperOre = 7,
        GoldOre = 8,
        SilverOre = 9,
        DemoniteOre = 22,
        Meteorite = 37,
        Obsidian = 56,
        Hellstone = 58,
        CobaltOre = 107,
        MythrilOre = 108,
        AdamantiteOre = 111,
        TinOre = 166,
        LeadOre = 167,
        TungstenOre = 168,
        PlatiniumOre = 169,
        PreciousStone = 178,

        // Loots
        CrystalHeart = 12,
        Chest = 21,
        Pot = 28,
        PiggyBank = 29,
        Orb = 31, // Shadow Orb or Crimson Heart
        Safe = 97,

        // Traps
        CorruptionThorny = 32,
        Spike = 48,
        JungleThorn = 69,
        PressurePlate = 135,
        Boulder = 138,

        // Buttons
        Lever = 132,
        Switch = 136,

        // Craft
        Bottle = 13,
        Anvil = 16,
        Furnace = 17,
        WorkBench = 18,
        Altar = 26,
        Hellforge = 77,
        Loom = 86,
        Keg = 94,
        CookingPot = 96,
        Sawmill = 106,
        Workshop = 114,
        Forge = 133,
        MythrilAnvil = 134,

        // Sign
        Sign = 55,

        // Bed
        Bed = 79,

        // Others
        ShortGrass = 3, // Also muchroom
        Torch = 4,
        Table = 14,
        Chair = 15,
        Acorn = 20,
        CorruptionPlant = 24, // Also corruption mushroom
        Sunflower = 27,
        Candle = 33,
        Chandelier = 34,
        JackOLantern = 35,
        Present = 36,
        Lantern = 42,
        WaterCandle = 49,
        Book = 50,
        Cobweb = 51,
        Vines = 52,
        ShortJungleGrass = 61,
        JungleVine = 62,
        GlowingMushroom = 71,
        GiantGlowingMushroom = 72,
        TallGrass = 73,
        TallJungleGrass = 74,
        ClayPot = 78,
        Cactus = 80,
        Coral = 81,
        FlowerGrowing = 82,
        FlowerMature = 83,
        FlowerBlooming = 84,
        Tombstone = 85,
        Piano = 87,
        Dresser = 88,
        Bench = 89,
        Bathtub = 90,
        Banner = 91,
        LampPost = 92,
        Lamp = 93, // Also contains Tiki torch
        ChineseLantern = 95,
        SkullLantern = 98,
        TrashCan = 99,
        Candelabra = 100,
        Bookcase = 101,
        Throne = 102,
        Bowl = 103,
        Clock = 104,
        Statue = 105,
        ShortHallowedGrass = 110,
        TallHallowedGrass = 113,
        HallowedVine = 115,
        CrystalBall = 125,
        DiscoBall = 126,
        Mannequin = 128,
        CrystalShard = 129,
        InactiveStoneBlock = 131,
        MusicBox = 139,
        Explosives = 141,
        InletPump = 142,
        OutletPump = 143,
        Toimer = 144,
        Light = 149,
        AmbiantObject = 165,
        ChristmasTree = 171,
        WoodenSink = 172,
        PlatiniumCandelabra = 173,
        PlatiniumCandle = 174,
        MossGrowth = 184,
        SmallAmbiantObject = 185,
        MediumAmbiantObject = 186,
        LargeAmbiantObject = 187,
    }
}
